# Generated by Django 2.0.6 on 2018-06-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aa',
        ),
    ]
