# Generated by Django 2.0.6 on 2018-06-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_aa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(choices=[('en', 'EN'), ('es', 'ES')], default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Article'),
        ),
    ]
