# Generated by Django 2.0.6 on 2018-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180615_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
